### ISSUE TITLE
列表首项与前行的间距过大问题

### ISSUE THREAD

**Issue by FLIER001** [shiyiya/typecho-theme-sagiri#24]
同样的，子列表首项与上一级列表的间距也被设定了同样大小的值
如下图，看起来很别扭：
![image](https://user-images.githubusercontent.com/26852784/63602464-15380700-c5fa-11e9-8a70-d91e17b8a814.png)

对css不太熟悉，不知道修改css哪一段代码可以解决？

**Comment by shiyiya** [comment]
```css
ul {
    padding-left: 20px;
}
```

**Comment by FLIER001** [comment]
> ```css
> ul {
>     padding-left: 20px;
> }
> ```

我想表达的是**不同级别列表之间的上下间距太大**，比如说2222和3333之间，3333和4444之间的间隔

**Comment by shiyiya** [comment]
```css
ul > li > p {
   margin: ??px 0;
}
```
