### ISSUE TITLE
代码块的首行错位问题

### ISSUE THREAD

**Issue by harry10086** [shiyiya/typecho-theme-sagiri#26]
一直发现代码块的首行和其他的行对不齐，不知道问题出在哪。
我在 index.min.css 文件里加了个就好了：
```css
pre code {
    display: block;
    background: 0 0;
    padding: 2px 2px;
}
```
